services:
  app:
    build: ./backend
    container_name: app-dev
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: react-dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container modules
    ports:
      - "3000:3000"
    stdin_open: true # Required for React scripts to stay open in some environments
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading in Docker volumes

volumes:
  postgres_data: